### ISSUE TITLE
Improve error message when trying to convert incompatible types [DATAMONGO-1034]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-mongodb#1957]
**[Ryan Bergman](https://jira.spring.io/secure/ViewProfile.jspa?name=ryber)** opened **[DATAMONGO-1034](https://jira.spring.io/browse/DATAMONGO-1034?redirect=false)** and commented

Hi!

This test project exposes a issue that started to show up in spring-data-mongodb when I migrated from 1.3.2 to 1.5.2. The MongoDB driver itself does not have this problem.

I have posted a working test showing it work in 1.3.2 and broken in 1.5.2 and 1.6.0. You can find them here:

https://github.com/ryber/spring-data-issue

This test loads the src/main/resources/source-data.json file into mongo and then attempts to read it out with Spring. It results in a error of:

Given DBObject must be a BasicDBObject! Object of class [com.mongodb.BasicDBList] must be an instance of class com.mongodb.BasicDBObject

I believe this is on the structure inside of GeoPointValue.

There are three branches of this repo:

132: works fine on 1.3.2
master: Broken on 1.5.2
160rc1: Still broken on 1.6.0.RC1

Note that in the real world The Foo struct is created by another (non-java) System and there are several TB of this collection, so Changing the actual document is not an option. However The spring app is read only so changing the mapping IS an option

---

**Affects:** 1.5.2 (Dijkstra SR2), 1.6 RC1 (Evans)

**Reference URL:** https://github.com/ryber/spring-data-issue

**Backported to:** [1.5.4 (Dijkstra SR4)](https://github.com/spring-projects/spring-data-mongodb/milestone/44?closed=1)
